name: LaTeX Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-science texlive-fonts-recommended texlive-fonts-extra texlive-lang-portuguese latexmk

      - name: Build LaTeX files
        run: |
          mkdir -p build
          export TEXINPUTS=".:${PWD}/latex_common//:${TEXINPUTS}:"
          find . -name "*.tex" -execdir latexmk -pdf -output-directory=build {} \;

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: "**/*.pdf"
      - name: Generate HTML Index
        run: |
            # Create an index.html file with links to all PDFs in the build directory
            echo "<html><body><h1>PDF List</h1><ul>" > build/index.html
            find build -name "*.pdf" | sed 's#build/##' | while read pdf; do
              echo "<li><a href=\"$pdf\">$(basename $pdf)</a></li>" >> build/index.html
            done
            echo "</ul></body></html>" >> build/index.html
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            force_orphan: true
            keep_files: false